class Constants:
    SCREEN_WIDTH = 800
    SCREEN_HEIGHT = 600

    TOP_HALF = SCREEN_HEIGHT / 2
    BOTTOM_HALF = - SCREEN_HEIGHT / 2
    RIGHT_HALF = SCREEN_WIDTH / 2
    LEFT_HALF = - SCREEN_WIDTH / 2

    RACKET_SIZE = 5
    RACKET_WIDTH = 20
    RACKET_HEIGHT = 20 * RACKET_SIZE
    RACKET_SPEED = 50

    RIGHT_PADDLE_AXIS = RIGHT_HALF - RACKET_WIDTH
    RIGHT_PADDLE_X = RIGHT_PADDLE_AXIS + (RACKET_WIDTH / 2)
    LEFT_PADDLE_AXIS = LEFT_HALF + RACKET_WIDTH
    LEFT_PADDLE_X = LEFT_PADDLE_AXIS - (RACKET_WIDTH / 2)

    BALL_SPEED = 5
    BALL_RADIUS = 20

    SCORE_GAP = 80
    RIGHT_SCORE_X = SCORE_GAP
    RIGHT_SCORE_Y = TOP_HALF - SCORE_GAP
    SCORE_TARGET = 7

    LEFT_SCORE_X = -SCORE_GAP
    LEFT_SCORE_Y = TOP_HALF - SCORE_GAP
